---
    - name: Remove Nginx configuration file
      file:
        path: /etc/nginx/nginx.conf
        state: absent

    - name: Fix nginx.conf path
      shell:
        cmd: mv /etc/nginx/nginx.conf*@* /etc/nginx/nginx.conf

    - name: Remove data directory
      file:
        path: /my-web-server
        state: absent

    - name: Stop Nginx service
      service:
        name: nginx
        state: stopped

